config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get   'cocktails', to: 'cocktails#index'

  # post  'cocktails', to: 'cocktails#create'
  # get   'cocktails/new', to: 'cocktails#new', as: 'new_cocktail'

  # get   'cocktails/:id', to: 'cocktails#show', as: 'cocktail'

  # get   'cocktails/:id/doses/new', to: 'doses#new', as: 'new_dose'
  # post  'cocktails/:id/doses', to: 'doses#create'

  root to:'cocktails#index'
  resources :cocktails, only: [:show, :new, :create] do
    resources :doses, only: [:new, :create]
  end

  delete 'doses/:id', to: 'doses#destroy', as: 'dose'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  # A dose must have a description, a cocktail and an ingredient,
  # and [cocktail, ingredient] pairings should be unique.
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @ingredients = Ingredient.all.order(:name)
  end

  def create
    # raise
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    # @dose = Dose.create({ description: '3cl', ingredient: Ingredient.first, cocktail: Cocktail.first })
    # raise
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail_id)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<% if @cocktails.empty? %>
  <p>No cocktail for now.</p>
<% else %>
  <div class="cocktails card-columns">
    <% @cocktails.each do |cocktail| %>

      <div class="card mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.2)),
      url('<%= cl_image_path(cocktail.photo, width: 400, height: 300, crop: :fill) %>')">
        <%= link_to cocktail_path(cocktail) do %>
        <div class="card-body text-white">
          <h3 class="card-title"><%= cocktail.name %></h3>
          <% if !cocktail.doses.empty? %>
            <p class="card-text">Ingredients : </p>
            <ul class= "card-text">
              <% cocktail.doses.each do |dose| %>
              <li><%= dose.description %> <%= dose.ingredient.name %></li>
              <% end %>
            </ul>
          <% end %>
          <%#= link_to "See more", cocktail_path(cocktail), class:'btn btn-primary' %>
        </div>
        <% end %>
      </div>


    <% end %>
  </div>
<% end %>
<%= link_to "Create new cocktail", new_cocktail_path, class:'btn btn-primary' %>

app/views/cocktails/new.html.erb
<div class="row justify-content-center">
  <div class="col col-md-6">
    <h1>Create a new cocktail</h1>
    <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name %>
      <%= f.input :description, as: :text %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.button :submit, "Add a new cocktail", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path(@cocktail.photo, crop: :fill) %>);">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
  </div>
</div>
<div class="row mt-4">
  <div class="col">
    <h2>Description</h2>
    <p><%= @cocktail.description %></p>
  </div>
  <div class="col">
    <% if @cocktail.doses.empty? %>
      <p> No recipe for this cocktail.</p>
    <% else %>
      <ul class="list-group">
      <% @cocktail.doses.each do |dose| %>
        <li class="list-group-item d-flex justify-content-between"><%= dose.ingredient.name %> : <%= dose.description %><%= link_to dose_path(dose), method: :delete do %> <i class="fa fa-trash text-danger" aria-hidden="true"></i><% end %></li>
      <% end %>
      </ul>
    <% end %>
    <%= link_to "Create a new dose", new_cocktail_dose_path(@cocktail), class:'btn btn-primary mt-3' %>
  </div>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/new.html.erb
<div class="row justify-content-center">
  <div class="col col-md-6">
    <h1>Create a new dose</h1>
    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.input :description %>
      <%= f.association :ingredient, collection: @ingredients %>
      <%= f.button :submit, "Add a new dose", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Mr NiCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container">
        <%= link_to root_path, class:'navbar-brand' do %>
          <img src="https://cdn0.iconfinder.com/data/icons/food-icons-rounded/110/Cocktail-512.png" />
          Mr NiCocktail
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "See all cocktails", root_path, class:'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Create new cocktail", new_cocktail_path, class:'nav-link'  %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container mt-4">
      <%= yield %>
    </div>


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>